services:
  resource-db:
    image: postgres:17
    container_name: resource-db
    environment:
      POSTGRES_DB: resource_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_RESOURCE_PORT}
    volumes:
      - resource-db-data:/var/lib/postgresql/data

  song-db:
    image: postgres:17
    container_name: song-db
    environment:
      POSTGRES_DB: song_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_SONG_PORT}
    volumes:
      - song-db-data:/var/lib/postgresql/data

volumes:
  resource-db-data:
  song-db-data:
