services:
  resource-db:
    image: postgres:17
    container_name: resource-db
    environment:
      POSTGRES_DB: ${POSTGRES_RESOURCE_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_RESOURCE_PORT}
    volumes:
      - resource-db-data:/var/lib/postgresql/data

  song-db:
    image: postgres:17
    container_name: song-db
    environment:
      POSTGRES_DB: ${POSTGRES_SONG_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_SONG_PORT}
    volumes:
      - song-db-data:/var/lib/postgresql/data


  resourceservice:
    build: ./resourceservice
    container_name: resource-service
    ports:
      - "8081:8081"
    depends_on:
      - resource-db
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  songservice:
    build: ./songservice
    container_name: song-service
    ports:
      - "8082:8082"
    depends_on:
      - song-db
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  resource-db-data:
  song-db-data:
