server:
  port: 8085

spring:
  application:
    name: storage-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/storage_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info

aws:
  region: ${CLOUD_AWS_REGION_STATIC:eu-west-3}

cloud:
  aws:
    region:
      static: ${CLOUD_AWS_REGION_STATIC:eu-west-3}
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY:test}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY:test}
    s3:
      endpoint: ${CLOUD_AWS_S3_ENDPOINT:http://localhost:4566}
      path-style-access: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

logging:
  level:
    root: INFO
    com.microservices: DEBUG
